### ISSUE TITLE
Strong reference to PanframeAsset causing memory issues

### ISSUE THREAD

**Issue by stuartpatt** [zmian/PanframeSDKWrapper#1]
When creating a Panframe asset, creating a strong reference that remains once `- (void) stop;
` & `- (bool) setTimeMonitor:(id<PFAssetTimeMonitor>) monitor;` set to nil along with the Panframe asset itself prior to dismissing a view controller.

![screen shot 2016-04-28 at 16 17 14](https://cloud.githubusercontent.com/assets/11421643/14891037/db511c10-0d5c-11e6-853f-2da95dd740ea.png)

![screen shot 2016-04-28 at 16 17 48](https://cloud.githubusercontent.com/assets/11421643/14891045/e8e76b40-0d5c-11e6-894f-f30c141daa5b.png)

**Comment by zmian** [comment]
thanks for reporting. Will investigate some time next week.

**Comment by zmian** [comment]
do you have a sample project to share with that memory issue?
